<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <NoWarn>NU1902;NU1903</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MailKit" Version="3.0.0" />
    </ItemGroup>

</Project>
